var car = "subaru";
console.log("Is car = 'subaru'? I predict true");
console.log(car == "subaru");
console.log("Is car = 'toyota'? I predict false");
console.log(car == "toyota");
var carType = "suv";
console.log("Is car type = 'suv'? I predict true");
console.log(carType == "suv");
console.log("Is car type = 'sports'? I predict false");
console.log(carType == "sports");
var fuelType = "hybride";
console.log("Is fuel type = 'hybride'? I predict true");
console.log(fuelType == "hybride");
console.log("Is fuel type = 'conventional ? I predict false");
console.log(fuelType == "conventional");
var powerSource = "combustion";
console.log("Is power source = 'combustion'? I predict true");
console.log(powerSource == "combustion");
console.log("Is power source = 'electric'? I predict flase");
console.log(powerSource == "electric");
var feature = "symmetrical";
console.log("Is featire = 'symmetrical'? I predict true");
console.log(feature == "symmetrical");
console.log("Is feature = 'non-symmetrical'? I predict false");
console.log(feature == "non-symmetrical");
